"use client";
import {useState,useEffect} from "react";
import { createClient } from "@supabase/supabase-js";
const supabase = createClient("https://rlsmcomxugstuoerdam.supabase.co","sb_publishable_mxCJKSppCAnMe6SwT7tbiQ_4dlOy122");
const LOGO="/k-logo.png";
const PKR=(d:number)=>`Rs. ${Number(d).toLocaleString()}`;
const ALL=[
{id:1,n:"Silk Blazer",pr:5490,cat:"FASHION",sub:"MALE",im:"https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400",colors:["#000","#D4B78F"],sizes:["M","L","XL"]},
{id:2,n:"Leather Bag",pr:6990,cat:"FASHION",sub:"FEMALE",im:"https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",colors:["#8B4513","#000"],sizes:["Free"]},
{id:3,n:"Male T-Shirt",pr:1290,cat:"FASHION",sub:"MALE",im:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",colors:["#000","#fff"],sizes:["M","L","XL"]},
{id:4,n:"Male Cap",pr:750,cat:"FASHION",sub:"MALE",im:"https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400",colors:["#000"],sizes:["Free"]},
{id:5,n:"Male Slippers",pr:990,cat:"FASHION",sub:"MALE",im:"https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=400",colors:["#000"],sizes:["40","41","42"]},
];
export default function Home(){
const [pg,setPg]=useState("home");const [cart,setCart]=useState<any[]>([]);const [user,setUser]=useState<any>(null);const [showLogin,setShowLogin]=useState(false);const [form,setForm]=useState({name:"",gmail:"",phone:""});const [otp,setOtp]=useState("");const [step,setStep]=useState(1);const [loading,setLoading]=useState(false);const [q,setQ]=useState("");const [sellerProds,setSellerProds]=useState<any[]>([]);
const [showOptions,setShowOptions]=useState<any>(null);const [selSize,setSelSize]=useState("M");const [selColor,setSelColor]=useState("");const [selQty,setSelQty]=useState(1);const [showCheckout,setShowCheckout]=useState(false);const [payType,setPayType]=useState("COD");const [buyerPhone,setBuyerPhone]=useState("");const [buyerName,setBuyerName]=useState("");const [locText,setLocText]=useState("");const [locLat,setLocLat]=useState<any>(null);const [locLng,setLocLng]=useState<any>(null);const [phoneOtp,setPhoneOtp]=useState("");const [phoneOtpSent,setPhoneOtpSent]=useState(false);
useEffect(()=>{const s=localStorage.getItem("kaiha_user");if(s){setUser(JSON.parse(s)); setBuyerName(JSON.parse(s).name); setBuyerPhone(JSON.parse(s).phone);} else setShowLogin(true); fetchHybrid();},[]);
const fetchHybrid=async()=>{try{const {data}=await supabase.from("products").select("*").eq("is_active",true).order("created_at",{ascending:false});const supa=(data||[]).map((d:any)=>({id:d.id,n:d.name||d.n,pr:d.price||d.pr,cat:(d.category||"FASHION").toUpperCase(),im:d.image_url||d.im,colors:d.colors? (typeof d.colors==='string'? d.colors.split(','):d.colors):["#000"],sizes:d.sizes? (typeof d.sizes==='string'? d.sizes.split(','):d.sizes):["M","L"],shopName:d.shop_name||"Seller Shop",campaign:d.campaign||"NONE",discount:d.discount||0}));const local=JSON.parse(localStorage.getItem("kaiha_all_products")||"[]").map((p:any)=>({id:p.id||Date.now(),n:p.name||p.n,pr:p.price||p.pr,cat:(p.category||"FASHION").toUpperCase(),im:p.image_url||p.image||p.im,colors:["#000"],sizes:["M","L"],shopName:p.shop_name||p.shopName||"Local Shop",campaign:p.campaign||"NONE",discount:p.discount||0}));setSellerProds([...supa,...local]);}catch(e){}};
const requireLogin=(fn:any)=>{if(!user){setShowLogin(true);setStep(1);return;}fn();};
const sendOtp=async()=>{const localOtp=Math.floor(100000+Math.random()*900000).toString();localStorage.setItem("kaiha_local_otp",localOtp);setStep(2);alert("OTP: "+localOtp+" or 123456");};
const verifyOtp=async()=>{const localOtp=localStorage.getItem("kaiha_local_otp");if((localOtp&&otp===localOtp)||otp==="123456"){const u={...form,id:Date.now()};localStorage.setItem("kaiha_user",JSON.stringify(u));setUser(u);setBuyerName(u.name);setBuyerPhone(u.phone);setShowLogin(false);}else alert("Wrong OTP");};
const openOptions=(p:any)=>{requireLogin(()=>{setShowOptions(p);setSelSize(p.sizes?.[0]||"M");setSelColor(p.colors?.[0]||"#000");setSelQty(1);});};
const confirmAdd=()=>{const item={...showOptions,aid:Date.now(),selSize,selColor,qty:selQty,finalPr:showOptions.discount?Math.round(showOptions.pr*(1-showOptions.discount/100)):showOptions.pr};setCart(c=>[...c,item]);setShowOptions(null);setPg("bag");};
const tot=cart.reduce((s:any,i:any)=>s+(i.finalPr||i.pr)*i.qty,0);
const getCurrentLoc=()=>{navigator.geolocation.getCurrentPosition((pos)=>{setLocLat(pos.coords.latitude);setLocLng(pos.coords.longitude);setLocText(`Lat:${pos.coords.latitude.toFixed(4)} Lng:${pos.coords.longitude.toFixed(4)} - Current Location`);});};
const sendPhoneOtp=()=>{const o=Math.floor(100000+Math.random()*900000).toString();localStorage.setItem("kaiha_phone_otp",o);setPhoneOtpSent(true);alert(`OTP: ${o}`);};
const placeOrder=async()=>{if(!buyerName||!buyerPhone||!locText)return alert("Name, Phone, Location zaruri");const savedOtp=localStorage.getItem("kaiha_phone_otp");if(phoneOtp!==savedOtp&&phoneOtp!=="123456")return alert("Wrong OTP");setLoading(true);try{for(let c of cart){await supabase.from("orders").insert({buyer_name:buyerName,buyer_phone:buyerPhone,buyer_gmail:user?.gmail,location_text:locText,location_lat:locLat,location_lng:locLng,product_name:c.n,product_image:c.im,quantity:c.qty,size:c.selSize,color:c.selColor,price:(c.finalPr||c.pr)*c.qty,payment_type:payType,status:"PENDING",seller_name:c.shopName});}setCart([]);setShowCheckout(false);setLoading(false);alert(`Order Placed! ${payType==="ONLINE"?"03320821575 pe bhejo":"Rider ayega"}`);setPg("home");}catch(e:any){setLoading(false);alert(e.message);}};
const filtered=[...ALL,...sellerProds].filter(p=>q?p.n.toLowerCase().includes(q.toLowerCase()):true);
 return(
<div style={{background:"#000",display:"flex",justifyContent:"center",minHeight:"100vh"}}>
<div style={{background:"#0a0a0a",width:"100%",maxWidth:"390px",minHeight:"100vh",paddingBottom:"90px",position:"relative",borderRadius:"28px",overflow:"hidden",color:"#fff"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 18px",borderBottom:"1px solid #1a1a1a"}}><div style={{display:"flex",alignItems:"center",gap:"12px"}}><img src={LOGO} style={{height:"44px",width:"44px",borderRadius:"12px"}}/><span style={{color:"#D4B78F",letterSpacing:"0.38em"}}>KAIHA</span></div></div>
{pg==="home"&&<div><div style={{padding:"12px 16px"}}><div style={{background:"#141414",borderRadius:"10px",height:"42px",display:"flex",alignItems:"center",padding:"0 14px",gap:"10px",border:"1px solid #D4B78F55"}}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..." style={{background:"transparent",border:"none",outline:"none",color:"#ccc",flex:1}}/></div></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",padding:"16px"}}>
{filtered.map((p:any)=>{const isFake=!p.shopName||ALL.some((a:any)=>a.id===p.id);return(<div key={p.id} style={{background:"#141414",borderRadius:"18px",padding:"8px",border:"1px solid #222",opacity:isFake?0.6:1}}><div style={{position:"relative"}}><img src={p.im} style={{width:"100%",height:"155px",borderRadius:"14px",objectFit:"cover",filter:isFake?"grayscale(0.7)":"none"}}/>{isFake&&<div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)",background:"#ff0000",color:"#fff",fontSize:"12px",padding:"5px 12px",borderRadius:"999px",fontWeight:"800"}}>SOLD</div>}<div style={{position:"absolute",top:"7px",left:"7px",background:isFake?"#ff0000":"#4CAF50",color:"#fff",fontSize:"7px",padding:"4px 8px",borderRadius:"999px"}}>{isFake?"SOLD":p.shopName}</div></div><div style={{fontSize:"12px",marginTop:"10px"}}>{p.n}</div><div style={{fontSize:"11px",color:"#D4B78F"}}>{PKR(p.discount?Math.round(p.pr*(1-p.discount/100)):p.pr)}</div>{isFake?<button disabled style={{width:"100%",marginTop:"10px",background:"#222",color:"#666",border:"1px solid #333",borderRadius:"999px",padding:"10px",fontSize:"10px"}}>SOLD OUT</button>:<button onClick={()=>openOptions(p)} style={{width:"100%",marginTop:"10px",border:"1px solid #D4B78F99",background:"none",color:"#D4B78F",borderRadius:"999px",padding:"10px",fontSize:"10px",fontWeight:"700"}}>ADD TO BAG</button>}</div>)})}
</div></div>}
{pg==="bag"&&<div style={{padding:"16px"}}><b>Bag ({cart.length}) {PKR(tot)}</b>{cart.length===0?<div style={{color:"#888",textAlign:"center",marginTop:"30px"}}>Empty</div>:<>{cart.map((c:any,i:number)=><div key={c.aid} style={{background:"#141414",borderRadius:"12px",padding:"12px",display:"flex",gap:"12px",marginTop:"10px"}}><img src={c.im} style={{width:"54px",height:"54px",borderRadius:"10px"}}/><div style={{flex:1}}><div style={{fontSize:"12px"}}>{c.n}</div><div style={{fontSize:"10px",color:"#aaa"}}>Qty:{c.qty}</div><div style={{fontSize:"10px",color:"#D4B78F"}}>{PKR((c.finalPr||c.pr)*c.qty)}</div></div><button onClick={()=>setCart(cart.filter((_:any,idx:number)=>idx!==i))} style={{background:"none",border:"1px solid #333",color:"#888",borderRadius:"999px",width:"28px",height:"28px"}}>✕</button></div>)}<button onClick={()=>setShowCheckout(true)} style={{width:"100%",marginTop:"16px",background:"#D4B78F",color:"#000",border:"none",padding:"14px",borderRadius:"999px",fontWeight:"800"}}>CHECKOUT → {PKR(tot)}</button></>}</div>}
<div style={{background:"#0a0a0a",borderTop:"1px solid #222",padding:"18px",marginTop:"30px",textAlign:"center",marginBottom:"80px"}}><div style={{fontSize:"11px",color:"#D4B78F",letterSpacing:"0.15em"}}>©2026 All Rights Reserved KAIHA HADI - SUKKUR</div></div>
<div style={{position:"fixed",bottom:0,left:"50%",transform:"translateX(-50%)",width:"100%",maxWidth:"390px",background:"rgba(15,15,15,0.98)",borderTop:"1px solid #222",borderRadius:"24px 24px 0 0",display:"flex",justifyContent:"space-around",padding:"12px 0 18px"}}><div onClick={()=>setPg("home")} style={{color:pg==="home"?"#D4B78F":"#6B6B6B"}}>⌂</div><div onClick={()=>setPg("bag")} style={{color:pg==="bag"?"#D4B78F":"#6B6B6B"}}>👜{cart.length>0?`(${cart.length})`:""}</div></div>
{showOptions&&<div style={{position:"fixed",inset:0,zIndex:300,background:"rgba(0,0,0,0.88)",display:"flex",alignItems:"flex-end",justifyContent:"center"}}><div style={{background:"#141414",width:"100%",maxWidth:"390px",borderRadius:"24px 24px 0 0",padding:"18px"}}><div style={{display:"flex",gap:"12px"}}><img src={showOptions.im} style={{width:"70px",height:"70px",borderRadius:"12px"}}/><div><div>{showOptions.n}</div><div style={{color:"#D4B78F"}}>{PKR(showOptions.pr)}</div></div><button onClick={()=>setShowOptions(null)} style={{marginLeft:"auto",background:"#222",border:"none",color:"#fff",width:"30px",height:"30px",borderRadius:"999px"}}>✕</button></div><button onClick={confirmAdd} style={{width:"100%",marginTop:"16px",background:"#D4B78F",color:"#000",border:"none",padding:"14px",borderRadius:"999px",fontWeight:"800"}}>ADD TO BAG - {PKR(showOptions.pr*selQty)}</button></div></div>}
{showCheckout&&<div style={{position:"fixed",inset:0,zIndex:400,background:"rgba(0,0,0,0.94)",display:"flex",alignItems:"center",justifyContent:"center",padding:"12px"}}><div style={{background:"#141414",width:"100%",maxWidth:"370px",borderRadius:"18px",padding:"16px",border:"1px solid #D4B78F44"}}><div style={{display:"flex",justifyContent:"space-between"}}><b>Checkout {PKR(tot)}</b><button onClick={()=>setShowCheckout(false)} style={{background:"#222",border:"none",color:"#fff",width:"28px",height:"28px",borderRadius:"999px"}}>✕</button></div><div style={{marginTop:"12px"}}><input value={buyerName} onChange={e=>setBuyerName(e.target.value)} placeholder="Full Name" style={{width:"100%",background:"#0a0a0a",border:"1px solid #333",borderRadius:"8px",padding:"10px",color:"#fff"}}/></div><div style={{marginTop:"8px",display:"flex",gap:"6px"}}><input value={buyerPhone} onChange={e=>setBuyerPhone(e.target.value)} placeholder="03XX-XXXXXXX" style={{flex:1,background:"#0a0a0a",border:"1px solid #333",borderRadius:"8px",padding:"10px",color:"#fff"}}/><button onClick={sendPhoneOtp} style={{background:"#fff",color:"#000",border:"none",borderRadius:"8px",padding:"10px"}}>OTP</button></div>{phoneOtpSent&&<input value={phoneOtp} onChange={e=>setPhoneOtp(e.target.value)} placeholder="123456" style={{width:"100%",background:"#0a0a0a",border:"1px solid #D4B78F",borderRadius:"8px",padding:"10px",color:"#fff",marginTop:"6px"}}/>}<div style={{marginTop:"8px",display:"flex",gap:"6px"}}><button onClick={getCurrentLoc} style={{flex:1,background:"#111",border:"1px solid #D4B78F44",color:"#D4B78F",borderRadius:"8px",padding:"10px",fontSize:"10px"}}>📍 Current Location</button><button onClick={()=>setLocText(prompt("Address")||"")} style={{flex:1,background:"#111",border:"1px solid #333",color:"#fff",borderRadius:"8px",padding:"10px",fontSize:"10px"}}>✏️ Select Location</button></div>{locText&&<div style={{fontSize:"10px",color:"#4CAF50",marginTop:"4px"}}>✅ {locText}</div>}<div style={{marginTop:"8px",display:"flex",gap:"8px"}}><button onClick={()=>setPayType("COD")} style={{flex:1,background:payType==="COD"?"#D4B78F":"#0a0a0a",color:payType==="COD"?"#000":"#fff",border:"1px solid #333",borderRadius:"10px",padding:"12px"}}>Pay Via Rider (COD)</button><button onClick={()=>setPayType("ONLINE")} style={{flex:1,background:payType==="ONLINE"?"#D4B78F":"#0a0a0a",color:payType==="ONLINE"?"#000":"#fff",border:"1px solid #333",borderRadius:"10px",padding:"12px"}}>Online 03320821575</button></div><button onClick={placeOrder} style={{width:"100%",marginTop:"14px",background:"#4CAF50",color:"#fff",border:"none",padding:"14px",borderRadius:"999px"}}>PLACE ORDER {PKR(tot)} →</button></div></div>}
{showLogin&&<div style={{position:"fixed",inset:0,zIndex:200,background:"rgba(0,0,0,0.92)",display:"flex",alignItems:"center",justifyContent:"center",padding:"16px"}}><div style={{background:"#141414",borderRadius:"16px",padding:"18px",width:"100%",maxWidth:"320px",border:"1px solid #D4B78F44"}}>{step===1?<><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full Name" style={{width:"100%",background:"#0a0a0a",border:"1px solid #333",borderRadius:"8px",padding:"10px",color:"#fff"}}/><input value={form.gmail} onChange={e=>setForm({...form,gmail:e.target.value})} placeholder="Gmail" style={{width:"100%",background:"#0a0a0a",border:"1px solid #333",borderRadius:"8px",padding:"10px",color:"#fff",marginTop:"8px"}}/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone" style={{width:"100%",background:"#0a0a0a",border:"1px solid #333",borderRadius:"8px",padding:"10px",color:"#fff",marginTop:"8px"}}/><button onClick={sendOtp} style={{width:"100%",marginTop:"12px",background:"#D4B78F",color:"#000",border:"none",padding:"11px",borderRadius:"999px"}}>SEND OTP</button></>:<><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="OTP 123456" style={{width:"100%",background:"#0a0a0a",border:"1px solid #D4B78F",borderRadius:"8px",padding:"12px",color:"#fff",textAlign:"center"}}/><button onClick={verifyOtp} style={{width:"100%",marginTop:"10px",background:"#D4B78F",color:"#000",border:"none",padding:"11px",borderRadius:"999px"}}>VERIFY</button></>}</div></div>}
</div></div>
);
 }
